---
networks:
  database:
    external: true

services:
  database:
    image: 'postgres'
    container_name: database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ${DATA}/database:/var/lib/postgresql/data/
    networks:
      - database
