watch:
  workers: 5
  schedule: "0 17 * * *"
  firstCheckNotif: false

providers:
  docker:
    watchByDefault: true

notif:
  telegram:
    token: aabbccdd:11223344
    chatIDs:
      - 123456789
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released.
