---
networks:
  proxy:
    external: true
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${STORAGE}/uptime:/app/data
    restart: always
    # ports:
    #   - 3001:3001
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`uptime.${DOMAIN}`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
    networks:
      - proxy
